env:
  browser: true
  es6: true
  jest: true 

extends:
  - airbnb

plugins:
  - prettier

rules: 
  class-methods-use-this: off
  import/no-name-as-default: off
  react/jsx-filename-extension: error
  extensions:
    - .js
    - .jsx
  semi:
    - error
    - always
  quotes: [error, "single", "avoid-escape", "allowTemplateLiterals"]
  prettier/prettier: error
  parser: babel-eslint
  parserOptions:
    ecmaVersion: 2019
    ecmaFeatures:
      jsx: true
    sourceType: module
